openapi: 3.0.0

# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Burhak/DayOffPlanner/1.0.0

info:
  title: Evolveum Day Off Planner API
  version: '1.0.0'

paths:
  /user/getAll:
    get:
      summary: Get all users
      operationId: getAllUsers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserApiModel'

  /login:
    post:
      summary: Logs user into the system
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginApiModel'
        description: Email and password for login
      responses:
        '200':
          description: successful operation
        '403':
          description: Invalid username/password supplied

components:
  schemas:
    UserApiModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string
            enum:
            - USER
            - ADMIN

    UserCreateApiModel:
      type: object
      required:
        - firstName
        - lastName
        - email
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        isAdmin:
          type: boolean
          default: false

    UserLoginApiModel:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string