version: "3.7"

services:
  rest:
    image: burhak/evo-day-off-planner-rest
    ports:
      - ${PORT}:9090
    container_name: rest
    volumes:
      - ./logs:/var/logs
    restart: always
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAILGUN_URL: ${MAILGUN_URL}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_EMAIL: ${MAILGUN_EMAIL}
    networks:
      internal_network:
        aliases:
          - rest

  db:
    image: postgres:12.1
    ports:
      - ${DB_PORT}:5432
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: evo-day-off-planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      internal_network:
        aliases:
          - db

networks:
  internal_network:
    name: internal_network
